title: PLEX
description: Making the Most of the Available Data for Robotic Manipulation Pretraining
authors: Anonymous
buttons:
  Paper: 'https://openreview.net/forum?id=Q8BGLiWn2X&noteId=Mi77W_EF2Y'
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
